-- ============================================================
-- OPT-IN demo data for weekly competitions
--
-- NOT a migration. This file lives outside supabase/migrations on purpose so
-- it can never run as part of a deploy or `supabase db push`.
--
-- It exists so a fresh environment (a preview deploy, a local database) opens
-- on a populated gallery instead of five empty states: a designer can see what
-- a submission, a vote, a comment and a results page actually look like.
--
-- Two guards, deliberately:
--
--   1. It refuses to do anything unless the session flag is set:
--        PGOPTIONS="-c app.competition_demo_seed=on" psql ...
--      so running the file by mistake is a no-op with a notice.
--   2. It only writes into competitions that have already started (never an
--      upcoming cycle) and skips any cycle that already has demo entries, so
--      running it twice does not pile data up.
--
-- Run it (with the flag) via the npm script:
--     npm run seed:competitions-demo
--
-- Remove everything it created, at any time:
--     delete from public.competition_entries where tags ? 'demo';
--     delete from public.competition_comments where body like '[demo]%';
--     delete from public.competition_participants where competition_id in
--       (select id from public.competitions);  -- only if you want to reset
--       the participant counts too
--   Entries cascade their own votes and bookmarks, so nothing is orphaned.
--
-- Every seeded entry is tagged "demo" in `tags`, which is visible on the entry
-- detail page — evidence of what the data is, not a hidden fixture.
--
-- Artwork comes from apps/web/public/competition-demo (generated by
-- scripts/generate-competition-demo-art.mjs), addressed as same-origin paths.
-- ============================================================

do $$
declare
  v_pool        uuid[];
  v_pool_size   int;
  v_competition record;
  v_designer    uuid;
  v_voter       uuid;
  v_entry_id    uuid;
  v_newest_week int;
  v_entries     int;
  v_cycle_seq   int := 0;
  v_global_seq  int := 0;
  v_entry_seq   int;
  v_art         int;
  v_extra       jsonb;
  v_featured    boolean;
  v_abstain     int;

  v_titles text[] := array[
    'Making the first screen decide',
    'Less data, more direction',
    'The quiet version',
    'One screen, one answer',
    'Ground-up redesign',
    'A softer default',
    'Type-first concept',
    'Fewer taps, more trust',
    'The ninety-second version',
    'Motion study',
    'Editorial pass',
    'Constraints first'
  ];

  v_descriptions text[] := array[
    'I started from the decision the screen has to support rather than the data behind it. Three passes later the hierarchy settled into one number, one sentence, and everything else pushed below the fold.',
    'The first version tried to say everything at once. This one picks a single point of view for the default state and lets people drill in when they actually want the detail.',
    'Most of the work went into restraint — removing the second and third competing focal points until what was left could be read in under two seconds.',
    'I designed the unusual case first (the messy day, the disrupted plan) and let the calm case fall out of it. It made the empty and error states much easier to defend.',
    'Built on a strict eight-point grid with a single accent, so the imagery carries the personality and the interface stays out of the way.',
    'The structure is deliberately plain: one primary action, one supporting fact, and a motion detail that explains where the next screen comes from.'
  ];

  -- jsonb[] so each element is already the JSON array the column wants.
  v_tools jsonb[] := array[
    '["Figma"]'::jsonb,
    '["Figma","After Effects"]'::jsonb,
    '["Figma","Illustrator"]'::jsonb,
    '["Figma","Framer"]'::jsonb,
    '["Photoshop","Figma"]'::jsonb
  ];

  v_tags jsonb[] := array[
    '["demo","mobile","typography"]'::jsonb,
    '["demo","mobile","motion"]'::jsonb,
    '["demo","mobile","dark-ui"]'::jsonb,
    '["demo","mobile","systems"]'::jsonb,
    '["demo","mobile","accessibility"]'::jsonb
  ];

  v_comments text[] := array[
    '[demo] The hierarchy here is the strongest part — I read it in one pass.',
    '[demo] Love the restraint. Did you try pushing the secondary type a step down?',
    '[demo] The motion detail at the end is what sells it for me.',
    '[demo] Really like the empty state treatment, that is usually where this kind of screen falls apart.',
    '[demo] Curious how this holds up with longer copy in the card.'
  ];
begin
  -- ── Guard 1: explicit opt-in only ──────────────────────────────────────
  if coalesce(current_setting('app.competition_demo_seed', true), '') <> 'on' then
    raise notice 'competitions-demo: skipped (set app.competition_demo_seed=on to seed).';
    return;
  end if;

  -- ── Guard 2: this needs a schedule and members to attribute to ─────────
  if not exists (select 1 from public.competitions) then
    raise notice 'competitions-demo: no competitions exist yet — run the competitions migration first.';
    return;
  end if;

  -- Real members, so the gallery shows real avatars, names and job titles.
  -- Designers with a profile come first, then everyone else by signup date.
  select array_agg(id order by rn) into v_pool
  from (
    select u.id, row_number() over (order by (dp.user_id is not null) desc, u.created_at) as rn
    from public.users u
    left join public.designer_profiles dp on dp.user_id = u.id
    where coalesce(u.is_blocked, false) = false
    limit 12
  ) ranked;

  v_pool_size := coalesce(array_length(v_pool, 1), 0);
  if v_pool_size < 2 then
    raise notice 'competitions-demo: needs at least 2 members to attribute entries and votes to (found %).', v_pool_size;
    return;
  end if;

  -- The most recent cycle that has actually started (an upcoming week is not
  -- a candidate for entries and should not be treated as "the current week").
  select max(week_number) into v_newest_week
  from public.competitions
  where start_at <= now();

  -- The live cycle plus the last three finished ones. Anything that has not
  -- started is left alone: nobody can submit to a challenge that is not open.
  for v_competition in
    select id, week_number
    from public.competitions
    where start_at <= now()
    order by week_number desc
    limit 4
  loop
    if exists (
      select 1
      from public.competition_entries e
      where e.competition_id = v_competition.id
        and e.tags ? 'demo'
    ) then
      continue;
    end if;

    -- The current week gets a fuller gallery; past weeks need enough to have
    -- produced a winner. Never more than there are members to attribute them
    -- to, or a designer would end up with two entries in the same week (which
    -- the one-entry-per-person trigger correctly refuses).
    v_entries := least(
      case when v_competition.week_number = v_newest_week then 6 else 4 end,
      v_pool_size
    );
    v_entry_seq := 0;

    while v_entry_seq < v_entries loop
      -- Steps by one per entry within the cycle (not by v_global_seq, which
      -- also advances) so no designer is picked twice in the same week — the
      -- per-user entry cap would reject that.
      v_designer := v_pool[1 + ((v_cycle_seq + v_entry_seq) % v_pool_size)];
      -- Every index below steps by one per entry within a cycle (offset by the
      -- cycle so weeks differ), so a week never repeats a title or an artwork.
      -- Stepping by v_global_seq as well would alias and produce duplicates.
      v_art := (v_cycle_seq * 5 + v_entry_seq) % 12;
      v_featured := v_competition.week_number <> v_newest_week and v_entry_seq = 0;
      v_abstain := (v_cycle_seq + v_entry_seq * 5) % 3;

      -- A couple of extra shots on some entries, so the detail page gallery
      -- is exercised too.
      v_extra := case
        when v_entry_seq % 3 = 0 then
          jsonb_build_array(
            jsonb_build_object(
              'name', 'Detail',
              'url', '/competition-demo/demo-' || lpad(((v_art + 5) % 12 + 1)::text, 2, '0') || '.svg',
              'type', 'image/svg+xml',
              'size', 0
            )
          )
        when v_entry_seq % 3 = 1 then
          jsonb_build_array(
            jsonb_build_object(
              'name', 'State',
              'url', '/competition-demo/demo-' || lpad(((v_art + 3) % 12 + 1)::text, 2, '0') || '.svg',
              'type', 'image/svg+xml',
              'size', 0
            ),
            jsonb_build_object(
              'name', 'Flow',
              'url', '/competition-demo/demo-' || lpad(((v_art + 7) % 12 + 1)::text, 2, '0') || '.svg',
              'type', 'image/svg+xml',
              'size', 0
            )
          )
        else '[]'::jsonb
      end;

      insert into public.competition_entries (
        competition_id, user_id, title, description,
        cover_image_url, design_image_url, image_urls,
        figma_url, prototype_url, tools, tags, is_featured
      )
      values (
        v_competition.id,
        v_designer,
        v_titles[1 + ((v_cycle_seq * 7 + v_entry_seq) % array_length(v_titles, 1))],
        v_descriptions[1 + ((v_cycle_seq * 5 + v_entry_seq) % array_length(v_descriptions, 1))],
        '/competition-demo/demo-' || lpad((v_art + 1)::text, 2, '0') || '.svg',
        '/competition-demo/demo-' || lpad((v_art + 1)::text, 2, '0') || '.svg',
        v_extra,
        null,
        null,
        v_tools[1 + ((v_cycle_seq * 2 + v_entry_seq) % array_length(v_tools, 1))],
        v_tags[1 + ((v_cycle_seq * 3 + v_entry_seq) % array_length(v_tags, 1))],
        v_featured
      )
      returning id into v_entry_id;

      insert into public.competition_participants (competition_id, user_id, first_action)
      values (v_competition.id, v_designer, 'entry')
      on conflict (competition_id, user_id) do nothing;

      -- ── Votes ────────────────────────────────────────────────────────
      -- Deterministic, so re-seeding an environment gives the same result,
      -- and never the designer's own entry (the database would reject it).
      for v_voter in
        select unnest(v_pool)
      loop
        if v_voter = v_designer then
          continue;
        end if;

        -- The first entry of a finished cycle is voted for by everyone, so
        -- each past week has an unambiguous winner to show on results day.
        -- Everything else takes most of the room, with a different handful
        -- abstaining per entry — so counts differ card to card instead of all
        -- reading as the same generated number.
        if v_featured
           or ((array_position(v_pool, v_voter) + v_entry_seq * 3) % (v_pool_size + 1)) > v_abstain
        then
          insert into public.competition_votes (competition_id, entry_id, user_id)
          values (v_competition.id, v_entry_id, v_voter)
          on conflict (competition_id, entry_id, user_id) do nothing;

          insert into public.competition_participants (competition_id, user_id, first_action)
          values (v_competition.id, v_voter, 'vote')
          on conflict (competition_id, user_id) do nothing;
        end if;
      end loop;

      -- ── A little discussion, so comment counts and the thread are real ──
      for v_voter in
        select unnest(v_pool)
        limit 2
      loop
        if v_voter = v_designer then
          continue;
        end if;

        insert into public.competition_comments (
          competition_id, entry_id, user_id, body
        )
        values (
          v_competition.id,
          v_entry_id,
          v_voter,
          v_comments[1 + ((v_cycle_seq + v_entry_seq * 2 + array_position(v_pool, v_voter)) % array_length(v_comments, 1))]
        );

        insert into public.competition_participants (competition_id, user_id, first_action)
        values (v_competition.id, v_voter, 'comment')
        on conflict (competition_id, user_id) do nothing;
      end loop;

      v_entry_seq := v_entry_seq + 1;
      v_global_seq := v_global_seq + 1;
    end loop;

    v_cycle_seq := v_cycle_seq + 1;
  end loop;

  raise notice 'competitions-demo: seeded % demo entries across the started cycles.', v_global_seq;
end $$;
