import nextConfig from "eslint-config-next";

/**
 * Global ignores.
 *
 * Without these, `eslint .` walked `.next/` and linted its own build output
 * (`[turbopack]_runtime.js`, `handler.mjs`, …). That produced ~22 errors
 * against generated code nobody wrote, and — because the build output is
 * large — pushed ESLint past Node's default heap and crashed
 * `npm run lint` with "JavaScript heap out of memory" (exit 134).
 *
 * This object must contain only `ignores` to act as a flat-config global
 * ignore, and it must come first in the array.
 */
const ignores = {
  ignores: [
    ".next/**",
    ".open-next/**",
    "node_modules/**",
    "out/**",
    "dist/**",
    "coverage/**",
    // Generated by Next.js / wrangler `cf-typegen` — not authored source.
    "next-env.d.ts",
    "cloudflare-env.d.ts",
    "*.tsbuildinfo",
  ],
};

const config = [ignores, ...nextConfig];

export default config;
