/**
 * Chat Message Flood
 *
 * Dedicated scenario for hammering the POST /messages endpoint as fast as
 * possible. No reactions, no reads, no cleanup — pure write throughput.
 * Every message is left in the community so you can observe count growth live.
 *
 * Each VU uses a pre-signed JWT from test-users.json (generated by
 * seed-users.js) so NO login calls are made and the IP rate limiter is
 * completely bypassed.
 *
 * Prerequisites:
 *   node k6/scripts/seed-users.js   ← must have run first
 *
 * Usage:
 *   k6 run k6/scenarios/chat_flood.js \
 *     -e BASE_URL=https://app.uxcommunity.in \
 *     -e TEST_COMMUNITY_ID=<uuid>
 *
 * Tuning:
 *   -e FLOOD_VUS=100          # concurrent senders (default 50)
 *   -e FLOOD_DURATION=5m      # how long to flood (default 3m)
 */

import http from 'k6/http';
import { check, sleep } from 'k6';
import { SharedArray } from 'k6/data';
import { Counter, Rate, Trend } from 'k6/metrics';
import { BASE_URL, JSON_HEADERS } from '../config.js';
import { loadSeededUsers } from '../utils/test-users.js';

// ── Users ─────────────────────────────────────────────────────────────────
const users = new SharedArray('flood-users', function () {
  return loadSeededUsers('../data/test-users.json');
});

// ── Config ────────────────────────────────────────────────────────────────
const COMMUNITY_ID = __ENV.TEST_COMMUNITY_ID || 'test-community-id';
const FLOOD_VUS    = parseInt(__ENV.FLOOD_VUS      || '500', 10);
const DURATION     = __ENV.FLOOD_DURATION          || '3m';
const MSG_URL      = `${BASE_URL}/api/communities/${COMMUNITY_ID}/messages`;

// ── Metrics ───────────────────────────────────────────────────────────────
const messagesSent   = new Counter('flood_messages_sent');
const messagesRejected = new Counter('flood_messages_rejected');
const sendTime       = new Trend('flood_send_ms', true);
const errorRate      = new Rate('flood_errors');

// ── Scenario ──────────────────────────────────────────────────────────────
export const options = {
  scenarios: {
    flood: {
      executor:  'constant-vus',
      vus:       FLOOD_VUS,
      duration:  DURATION,
      // All VUs start at the same time — simultaneous burst from the first second
      startTime: '0s',
    },
  },
  thresholds: {
    flood_send_ms:       ['p(95)<5000'],
    flood_errors:        ['rate<0.40'], // 429s expected when 500 users blast at once
    http_req_failed:     ['rate<0.40'],
  },
};

// ── Helpers ───────────────────────────────────────────────────────────────
const PHRASES = [
  'Anyone else working on something new this week?',
  'Just shipped a redesign — feedback welcome!',
  'Hot take: serif fonts are making a comeback.',
  'What tools are you using for handoff these days?',
  'Struggling with dark mode contrast — any tips?',
  'New portfolio drop 🔥',
  'Design systems save lives, fight me.',
  'Just joined this community — excited to be here!',
  "What's everyone's go-to prototyping tool right now?",
  'Figma auto-layout still breaks my brain sometimes.',
  'Anyone going to Config this year?',
  "Dark mode > light mode, don't @ me.",
  'Trying out a new grid system — game changer.',
  'Finally got my portfolio site to load under 1s.',
  'Motion design is so underrated in product work.',
  'Accessibility first, always.',
  'Just landed my first full-time design role 🎉',
  'Open to feedback on my latest case study.',
  'The best design is invisible.',
  'Responsive typography is genuinely hard.',
];

function randomMsg(vu, iter) {
  const phrase = PHRASES[(vu + iter) % PHRASES.length];
  return `[VU ${vu} · iter ${iter}] ${phrase}`;
}

function injectSession(token) {
  http.cookieJar().set(BASE_URL, 'uxcommunity_session', token, { path: '/' });
}

// ── Main loop ─────────────────────────────────────────────────────────────
export default function () {
  const user = users[(__VU - 1) % users.length];
  injectSession(user.sessionToken);

  const start = Date.now();
  const res   = http.post(
    MSG_URL,
    JSON.stringify({ content: randomMsg(__VU, __ITER) }),
    { headers: JSON_HEADERS, tags: { name: 'flood/send' } },
  );
  sendTime.add(Date.now() - start);

  const ok = check(res, {
    'flood/send: 201 or 429': (r) => r.status === 201 || r.status === 429,
  });

  if (res.status === 201) {
    messagesSent.add(1);
  } else if (res.status === 429) {
    messagesRejected.add(1);
  } else {
    errorRate.add(1);
  }

  if (!ok && res.status !== 429) {
    errorRate.add(1);
  }

  // Minimal think-time — just enough to avoid hammering the same user
  // account into per-user rate limits (5 msgs / 10s per user).
  // With 50 VUs each sleeping 2s, peak send rate ≈ 25 msg/s.
  sleep(2);
}
