name = "uxcommunity-realtime-staging"
main = "src/index.ts"
compatibility_date = "2026-08-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[durable_objects]
bindings = [
  { name = "COMMUNITY_DO", class_name = "Room" },
  { name = "USER_DO", class_name = "UserDO" },
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Room"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["UserDO"]

[[migrations]]
tag = "v3"
new_sqlite_classes = []

[vars]
USE_WEBSOCKET_OWNERSHIP = "false"
