/**
 * Pure helpers for the 5K same-community realtime fan-out test.
 *
 * WHY THIS EXISTS
 *   The first revision of `k6/loadtest-5k.mjs` counted a "delivery" as any
 *   `{t:"event"}` frame that arrived after a publish, per socket, with no event
 *   identity. That cannot tell "5,000 sockets are connected" from "5,000 sockets
 *   received event X", and it silently counts one socket's duplicate frame as a
 *   second successful delivery. The accounting here is the opposite: every
 *   published event carries an id, and every socket keeps a fixed-size bitmap of
 *   the event sequence numbers it received, so per-event delivery, missing and
 *   duplicate counts are EXACT and memory-bounded (eventCount bytes per socket,
 *   never one object per delivery).
 *
 *   Kept dependency-free (no `ws`, no `jose`, no k6 globals) so the accounting
 *   can be unit-tested without a network, a Worker or a Cloudflare account:
 *   `npm run test:k6-realtime`.
 */

/** Sequence numbers per event that a delivery bitmap can hold. */
export const MAX_TRACKED_EVENTS = 4096;

/**
 * Upper bound on comparable delivery latencies per event. Every replica stores
 * at most `capacity` samples, so a run cannot grow its memory with traffic.
 */
export const MAX_LATENCY_SAMPLES = 20_000;

/** Latency histogram edges in ms, used for the delivered-latency breakdown. */
export const LATENCY_BUCKETS = [
  { label: "<25ms", max: 25 },
  { label: "<50ms", max: 50 },
  { label: "<100ms", max: 100 },
  { label: "<250ms", max: 250 },
  { label: "<500ms", max: 500 },
  { label: "<1s", max: 1000 },
  { label: "<2s", max: 2000 },
  { label: "<5s", max: 5000 },
  { label: ">=5s", max: Number.POSITIVE_INFINITY },
];

/** Nearest-rank percentile of an unsorted numeric array. */
export function percentile(values, p) {
  if (!values || values.length === 0) return 0;
  const sorted = [...values].sort((a, b) => a - b);
  const index = Math.ceil((p / 100) * sorted.length) - 1;
  return sorted[Math.min(Math.max(index, 0), sorted.length - 1)];
}

/**
 * Distinct-value summary of a sample array. Returns null for an empty sample so
 * callers can print "not measured" instead of a fabricated 0ms.
 */
export function summarizeSamples(values) {
  const samples = (values ?? []).filter((value) => Number.isFinite(value));
  if (samples.length === 0) return null;
  const total = samples.reduce((sum, value) => sum + value, 0);
  return {
    count: samples.length,
    min: Math.min(...samples),
    max: Math.max(...samples),
    mean: Math.round(total / samples.length),
    p50: percentile(samples, 50),
    p90: percentile(samples, 90),
    p95: percentile(samples, 95),
    p99: percentile(samples, 99),
  };
}

/** Count samples per LATENCY_BUCKET (each sample lands in exactly one bucket). */
export function bucketize(values) {
  const samples = (values ?? []).filter((value) => Number.isFinite(value));
  return LATENCY_BUCKETS.map((bucket, index) => {
    const lower = index === 0 ? Number.NEGATIVE_INFINITY : LATENCY_BUCKETS[index - 1].max;
    return {
      label: bucket.label,
      count: samples.filter((value) => value > lower && value <= bucket.max).length,
    };
  });
}

/** Event ids are `"<testId>#<seq>"` — unique per published event, no zero-pad. */
export function makeEventId(testId, seq) {
  return `${testId}#${seq}`;
}

/**
 * Recover the sequence number from an event id. Returns null for anything that
 * is not this run's event — another run's traffic on the same community must
 * not be counted as a delivery of this run's event.
 */
export function parseEventId(eventId, testId) {
  if (typeof eventId !== "string") return null;
  const prefix = `${testId}#`;
  if (!eventId.startsWith(prefix)) return null;
  const seq = Number(eventId.slice(prefix.length));
  return Number.isInteger(seq) && seq >= 0 ? seq : null;
}

/**
 * Find this run's event marker inside a free-form string.
 *
 * The server-side publish path carries the event id in `data.id`, but events
 * that are generated by the application API (`POST /api/communities/:id/messages`)
 * are shaped by the app, so the only place a test marker survives is the message
 * text. Accepting both keeps the accounting honest either way.
 */
export function parseEventMarker(value, testId) {
  if (typeof value !== "string") return null;
  const index = value.indexOf(`${testId}#`);
  if (index === -1) return null;
  const rest = value.slice(index + testId.length + 1);
  const match = /^(\d+)/.exec(rest);
  if (!match) return null;
  const seq = Number(match[1]);
  return Number.isInteger(seq) && seq >= 0 ? seq : null;
}

function fnv1a(value) {
  let hash = 0x811c9dc5;
  for (let i = 0; i < value.length; i += 1) {
    hash ^= value.charCodeAt(i);
    hash = Math.imul(hash, 0x01000193) >>> 0;
  }
  return hash >>> 0;
}

/**
 * Deterministic, RFC-4122-v4-shaped user id for a client index.
 *
 * Deterministic on purpose: every stage of the ladder (100 → 5,000) then
 * authenticates the SAME identity set, so a stage's numbers are comparable with
 * the previous stage's instead of being a fresh population. The lower 12 hex
 * digits carry the index; the rest come from two FNV-1a passes over the prefix,
 * so ids stay distinct without a random generator.
 */
export function userIdForIndex(index, prefix = "h3k6") {
  if (!Number.isInteger(index) || index < 0) {
    throw new Error(`userIdForIndex needs a non-negative integer index, got ${index}`);
  }
  const a = fnv1a(`${prefix}:${index}`).toString(16).padStart(8, "0");
  const b = fnv1a(`${prefix}:${index}:b`).toString(16).padStart(8, "0");
  const c = fnv1a(`${prefix}:${index}:c`).toString(16).padStart(8, "0");
  const group1 = a; // 8 hex
  const group2 = b.slice(0, 4); // 4 hex
  const group3 = `4${b.slice(4, 7)}`; // version 4 + 3 hex
  const group4 = `a${c.slice(0, 3)}`; // variant 10xx + 3 hex
  const group5 = `${c.slice(3, 8)}${a}${b.slice(7)}`.slice(0, 12); // 12 hex
  return `${group1}-${group2}-${group3}-${group4}-${group5}`;
}

/**
 * Refuse to aim a 5,000-socket test at a host that is not an obvious staging
 * target. The previous revision defaulted to `wss://rt.uxcommunity.in`
 * (production) and only mentioned staging in a comment.
 */
export function assertStagingTarget(rawUrl, { allowNonStaging = false } = {}) {
  let host;
  try {
    host = new URL(rawUrl.replace(/^wss:/, "https:").replace(/^ws:/, "http:")).hostname;
  } catch {
    return { ok: false, reason: `REALTIME_URL is not a valid URL: ${rawUrl}` };
  }

  const looksLikeStaging =
    host.includes("staging") ||
    host.includes("localhost") ||
    host.endsWith(".workers.dev");

  if (looksLikeStaging || allowNonStaging) return { ok: true, host };
  return {
    ok: false,
    host,
    reason:
      `${host} does not look like a staging target. This test opens thousands of ` +
      "sockets and publishes real events, so it must not be pointed at production. " +
      "Set ALLOW_NON_STAGING=1 only if you are certain the target is disposable.",
  };
}

/**
 * Exact per-event delivery accounting for N sockets × K events.
 *
 * Every socket owns one row of the bitmap; `record` is the only writer, so
 * "received", "missing" and "duplicate" are exact counts — not samples.
 */
export class DeliveryTracker {
  /**
   * @param {{ eventCount: number, capacity: number }} options
   *   eventCount — how many events this run will publish
   *   capacity   — how many sockets may report deliveries
   */
  constructor({ eventCount, capacity }) {
    if (!Number.isInteger(eventCount) || eventCount <= 0) {
      throw new Error(`DeliveryTracker needs eventCount >= 1, got ${eventCount}`);
    }
    if (eventCount > MAX_TRACKED_EVENTS) {
      throw new Error(`eventCount ${eventCount} exceeds MAX_TRACKED_EVENTS (${MAX_TRACKED_EVENTS})`);
    }
    if (!Number.isInteger(capacity) || capacity <= 0) {
      throw new Error(`DeliveryTracker needs capacity >= 1, got ${capacity}`);
    }
    this.eventCount = eventCount;
    this.capacity = capacity;
    /** eventCount rows × capacity columns, 1 byte per (event, socket) pair. */
    this.received = new Uint8Array(eventCount * capacity);
    /** First-arrival latency per (event, socket), or NaN when not delivered. */
    this.latency = new Float64Array(eventCount * capacity).fill(Number.NaN);
    this.duplicatesByEvent = new Array(eventCount).fill(0);
    this.totalDuplicates = 0;
    this.totalReceived = 0;
    this.unmatchedFrames = 0;
  }

  /**
   * Record one delivery frame.
   *
   * @returns {"first" | "duplicate" | null} `first` when this socket had not
   *   received this event yet, `duplicate` when it already had, null when the
   *   args are out of range (never counted as a delivery).
   */
  record(clientIndex, seq, latencyMs) {
    if (!Number.isInteger(seq) || seq < 0 || seq >= this.eventCount) return null;
    if (!Number.isInteger(clientIndex) || clientIndex < 0 || clientIndex >= this.capacity) return null;

    const offset = seq * this.capacity + clientIndex;
    if (this.received[offset] === 1) {
      this.duplicatesByEvent[seq] += 1;
      this.totalDuplicates += 1;
      return "duplicate";
    }

    this.received[offset] = 1;
    this.totalReceived += 1;
    if (Number.isFinite(latencyMs)) this.latency[offset] = latencyMs;
    return "first";
  }

  /** Count a frame that carried no id of this run (another run, or malformed). */
  recordUnmatched() {
    this.unmatchedFrames += 1;
  }

  /** Sockets that received at least one event. */
  get receivers() {
    let receivers = 0;
    for (let client = 0; client < this.capacity; client += 1) {
      for (let seq = 0; seq < this.eventCount; seq += 1) {
        if (this.received[seq * this.capacity + client] === 1) {
          receivers += 1;
          break;
        }
      }
    }
    return receivers;
  }

  receivedFor(seq) {
    this.assertSeq(seq);
    let count = 0;
    for (let client = 0; client < this.capacity; client += 1) {
      count += this.received[seq * this.capacity + client];
    }
    return count;
  }

  duplicatesFor(seq) {
    this.assertSeq(seq);
    return this.duplicatesByEvent[seq];
  }

  /** Sockets that did NOT receive `seq`, given how many were expected to. */
  missingFor(seq, expected) {
    return Math.max(0, expected - this.receivedFor(seq));
  }

  latenciesFor(seq) {
    this.assertSeq(seq);
    const samples = [];
    for (let client = 0; client < this.capacity; client += 1) {
      const value = this.latency[seq * this.capacity + client];
      if (Number.isFinite(value)) samples.push(value);
    }
    return samples;
  }

  /** Delay between the first and the last delivery of one event (fan-out spread). */
  fanoutSpanFor(seq) {
    const samples = this.latenciesFor(seq);
    if (samples.length === 0) return null;
    return Math.round(Math.max(...samples) - Math.min(...samples));
  }

  /** Every finite latency sample across all events, bounded by tracker size. */
  allLatencies() {
    const samples = [];
    for (let offset = 0; offset < this.latency.length; offset += 1) {
      const value = this.latency[offset];
      if (Number.isFinite(value)) samples.push(value);
    }
    return samples;
  }

  assertSeq(seq) {
    if (!Number.isInteger(seq) || seq < 0 || seq >= this.eventCount) {
      throw new Error(`event sequence ${seq} is out of range (0..${this.eventCount - 1})`);
    }
  }
}
