export const communityFeedLayout = {
  content: "mx-auto w-full max-w-[40rem]",
  detailContent: "mx-auto w-full max-w-[40rem]",
  gutters: "px-5 md:px-8",
  pageHeader: "px-5 py-7 md:px-8",
  pageHeaderWithFilters: "px-5 pb-2 pt-7 md:px-8",
  pageHeaderMain: "flex min-w-0 items-start justify-between gap-3",
  pageHeaderFilters: "mt-6",
  row: "px-5 py-6 md:px-8",
  cardList: "flex flex-col gap-4 px-5 pb-6 md:px-8",
  card: "overflow-hidden rounded-xl border border-border bg-surface px-5 py-5 md:px-6",
  cardInteractive: "transition-colors hover:bg-surface-raised/40 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent focus-visible:ring-offset-2 focus-visible:ring-offset-background",
  detailCard: "overflow-hidden rounded-xl border border-border bg-surface px-5 py-6 md:px-8",
  detailPage: "py-6",
  detailSection: "px-5 md:px-8",
  sectionLabel: "px-5 md:px-8",
  dividerList: "relative before:pointer-events-none before:absolute before:inset-x-0 before:top-0 before:border-t before:border-border",
  dividerBottom: "relative after:pointer-events-none after:absolute after:inset-x-0 after:bottom-0 after:border-b after:border-border",
  dividerY: "relative before:pointer-events-none before:absolute before:inset-x-0 before:top-0 before:border-t before:border-border after:pointer-events-none after:absolute after:inset-x-0 after:bottom-0 after:border-b after:border-border",
  emptyState: "relative flex min-h-52 flex-col items-center justify-center px-6 py-12 text-center",
  emptyIcon: "mb-4 text-foreground-subtle",
  emptyTitle: "font-display text-base font-semibold text-foreground",
  emptyDescription: "mt-1 max-w-md text-pretty font-body text-sm leading-6 text-foreground-muted",
} as const;
