export const communityFeedLayout = {
  content: "mx-auto w-full max-w-4xl",
  detailContent: "mx-auto w-full max-w-4xl",
  gutters: "px-5 md:px-8",
  pageHeader: "px-5 py-7 md:px-8",
  pageHeaderMain: "flex min-w-0 items-start justify-between gap-3",
  pageHeaderFilters: "mt-6",
  row: "px-5 py-6 md:px-8",
  detailPage: "py-6",
  detailSection: "px-5 md:px-8",
  sectionLabel: "px-5 md:px-8",
  dividerList: "relative before:pointer-events-none before:absolute before:inset-x-0 before:top-0 before:border-t before:border-border",
  dividerBottom: "relative after:pointer-events-none after:absolute after:inset-x-0 after:bottom-0 after:border-b after:border-border",
  dividerY: "relative before:pointer-events-none before:absolute before:inset-x-0 before:top-0 before:border-t before:border-border after:pointer-events-none after:absolute after:inset-x-0 after:bottom-0 after:border-b after:border-border",
  emptyState: "relative flex min-h-52 flex-col items-center justify-center px-6 py-12 text-center before:pointer-events-none before:absolute before:inset-x-0 before:top-0 before:border-t before:border-border after:pointer-events-none after:absolute after:inset-x-0 after:bottom-0 after:border-b after:border-border",
  emptyIcon: "mb-4 text-foreground-subtle",
  emptyTitle: "font-display text-base font-semibold text-foreground",
  emptyDescription: "mt-1 max-w-md text-pretty font-body text-sm leading-6 text-foreground-muted",
  skeletonList: "relative animate-pulse before:pointer-events-none before:absolute before:inset-x-0 before:top-0 before:border-t before:border-border",
  skeletonRow: "relative px-5 py-6 after:pointer-events-none after:absolute after:inset-x-0 after:bottom-0 after:border-b after:border-border md:px-8",
  skeletonLine: "rounded bg-surface-raised",
} as const;
