export const communityFeedLayout = {
  content: "mx-auto w-full max-w-4xl",
  detailContent: "mx-auto w-full max-w-3xl",
  gutters: "px-4 sm:px-6 lg:px-16",
  pageHeader: "px-4 py-6 sm:px-6 lg:px-16",
  row: "px-4 py-6 sm:px-6 lg:px-16",
  detailPage: "px-4 py-6 sm:px-6 lg:px-16",
  dividerList: "relative before:pointer-events-none before:absolute before:left-1/2 before:top-0 before:w-screen before:-translate-x-1/2 before:border-t before:border-border",
  dividerBottom: "relative after:pointer-events-none after:absolute after:bottom-0 after:left-1/2 after:w-screen after:-translate-x-1/2 after:border-b after:border-border",
  dividerY: "relative before:pointer-events-none before:absolute before:left-1/2 before:top-0 before:w-screen before:-translate-x-1/2 before:border-t before:border-border after:pointer-events-none after:absolute after:bottom-0 after:left-1/2 after:w-screen after:-translate-x-1/2 after:border-b after:border-border",
  emptyState: "relative flex min-h-52 flex-col items-center justify-center px-6 py-12 text-center before:pointer-events-none before:absolute before:left-1/2 before:top-0 before:w-screen before:-translate-x-1/2 before:border-t before:border-border after:pointer-events-none after:absolute after:bottom-0 after:left-1/2 after:w-screen after:-translate-x-1/2 after:border-b after:border-border",
  emptyIcon: "mb-4 text-foreground-subtle",
  emptyTitle: "font-display text-base font-semibold text-foreground",
  emptyDescription: "mt-1 max-w-md text-pretty font-body text-sm leading-6 text-foreground-muted",
  skeletonList: "relative animate-pulse before:pointer-events-none before:absolute before:left-1/2 before:top-0 before:w-screen before:-translate-x-1/2 before:border-t before:border-border",
  skeletonRow: "relative px-4 py-6 after:pointer-events-none after:absolute after:bottom-0 after:left-1/2 after:w-screen after:-translate-x-1/2 after:border-b after:border-border sm:px-6 lg:px-16",
  skeletonLine: "rounded bg-surface-raised",
} as const;
