/**
 * Load and validate the private user/session file generated by seed-users.js.
 *
 * The file is intentionally gitignored because it contains session tokens.
 * Keep this validation close to the k6 scenarios so a bad local file produces
 * an actionable message instead of k6's low-level JSON parser error.
 */
import { FIXTURE_PATH, MISSING_FIXTURE_HINT, validateFixture } from '../lib/fixture.js';

export function loadSeededUsers(filePath) {
  let raw;

  try {
    raw = open(filePath);
  } catch {
    // open() throws before we ever see the contents when the file is missing,
    // so translate it into the same setup instructions as a bad file.
    throw new Error(`${FIXTURE_PATH} was not found.\n${MISSING_FIXTURE_HINT}`);
  }

  let users;

  try {
    users = JSON.parse(raw);
  } catch {
    throw new Error(
      `${FIXTURE_PATH} is not valid JSON.\n${MISSING_FIXTURE_HINT}\n` +
      '  Do not put an email address directly in this file.',
    );
  }

  // Shape, empty-credential, and entry-count rules live in k6/lib/fixture.js so
  // the seeder, the Node test, and the scenarios cannot drift apart.
  return validateFixture(users);
}
