/**
 * Load and validate the private user/session file generated by seed-users.js.
 *
 * The file is intentionally gitignored because it contains session tokens.
 * Keep this validation close to the k6 scenarios so a bad local file produces
 * an actionable message instead of k6's low-level JSON parser error.
 */
export function loadSeededUsers(filePath) {
  const raw = open(filePath);
  let users;

  try {
    users = JSON.parse(raw);
  } catch {
    throw new Error(
      'k6/data/test-users.json is not valid JSON. ' +
      'Run Seed Users from the admin panel to regenerate it; ' +
      'do not put an email address directly in this file.',
    );
  }

  if (!Array.isArray(users) || users.length === 0) {
    throw new Error(
      'k6/data/test-users.json must contain a non-empty array generated by ' +
      'k6/scripts/seed-users.js. Run Seed Users from the admin panel first.',
    );
  }

  for (let index = 0; index < users.length; index += 1) {
    const user = users[index];
    if (!user || typeof user !== 'object' || typeof user.sessionToken !== 'string' || !user.sessionToken) {
      throw new Error(
        `k6/data/test-users.json entry ${index + 1} has no sessionToken. ` +
        'Run Seed Users again so the file includes pre-signed sessions.',
      );
    }
  }

  return users;
}