-- ============================================================
-- Migration: the curated MNC company directory (the work-field list)
--
-- GENERATED FILE — do not edit by hand.
--   node scripts/generate-company-directory-mnc-seed.mjs
--   Source: data/company-directory/mnc-companies.json (573 companies)
--
-- WHAT THIS ADDS
--   573 well-known employers across the US, Europe and India, where
--   designers work: one `companies` row each and one UNVERIFIED
--   `company_domains` hint. A hint is not a claim — it makes the company
--   appear in the "Where do you work?" picker and lets the first member whose
--   work email matches finish the claim through the ordinary OTP flow. It never
--   writes `verified`.
--
-- WHY A MIGRATION AND NOT THE IMPORT
--   The 500,000-company import (scripts/import-company-directory.mjs) is a
--   separate, later phase. Until it runs the directory would otherwise be
--   empty. This is the one-time curated list; the admin page
--   (app/admin/(protected)/companies, /api/admin/companies) manages the same
--   two tables at runtime, so an add or a delete there shows in the picker
--   immediately and never needs a second source of truth.
--
-- IDEMPOTENT
--   `on conflict (slug) do nothing` and `on conflict (company_id, domain) do
--   nothing`: re-running never duplicates a row and never overwrites a
--   member's proof (a verified domain on the same pair is left untouched).
--
-- ALSO
--   Removes accidental one-character test companies (a single-letter name is
--   never a real employer) that were created by hand while exercising the
--   picker.
-- ============================================================

-- ─── Preconditions ──────────────────────────────────────────

-- The seed writes the stewardship columns (country_code, industry, source). A
-- database that has not applied that migration would otherwise fail on the
-- first INSERT with a bare "column does not exist"; say what to do instead.
do $mnc_seed_preconditions$
begin
  if to_regclass('public.companies') is null
     or to_regclass('public.company_domains') is null
     or not exists (
       select 1 from information_schema.columns
        where table_schema = 'public' and table_name = 'companies' and column_name = 'source'
     ) then
    raise exception using
      errcode = 'P0001',
      message = 'mnc_seed_needs_stewardship_schema',
      hint = 'apply 20260929120000_company_verified_domains.sql, then 20260929130000_company_directory_hints.sql, then 20260929150000_company_domain_stewardship.sql before this seed';
  end if;
end
$mnc_seed_preconditions$;


-- ─── The list, and the two inserts ──────────────────────────

do $mnc_seed$
declare
  v_companies integer;
  v_domains   integer;
begin
  create temporary table _mnc_seed (
    name     text not null,
    domain   text not null,
    country  text,
    industry text,
    rank     integer not null
  ) on commit drop;

  insert into _mnc_seed (name, domain, country, industry, rank) values
    ('Google', 'google.com', 'US', 'internet', 1),
    ('Microsoft', 'microsoft.com', 'US', 'software', 2),
    ('Apple', 'apple.com', 'US', 'consumer electronics', 3),
    ('Amazon', 'amazon.com', 'US', 'retail', 4),
    ('Meta', 'meta.com', 'US', 'internet', 5),
    ('Netflix', 'netflix.com', 'US', 'streaming', 6),
    ('Adobe', 'adobe.com', 'US', 'software', 7),
    ('NVIDIA', 'nvidia.com', 'US', 'semiconductors', 8),
    ('Intel', 'intel.com', 'US', 'semiconductors', 9),
    ('IBM', 'ibm.com', 'US', 'IT services', 10),
    ('Oracle', 'oracle.com', 'US', 'software', 11),
    ('Salesforce', 'salesforce.com', 'US', 'software', 12),
    ('Cisco', 'cisco.com', 'US', 'networking', 13),
    ('Dell Technologies', 'dell.com', 'US', 'hardware', 14),
    ('Hewlett Packard Enterprise', 'hpe.com', 'US', 'hardware', 15),
    ('HP', 'hp.com', 'US', 'hardware', 16),
    ('Uber', 'uber.com', 'US', 'mobility', 17),
    ('Airbnb', 'airbnb.com', 'US', 'travel', 18),
    ('Stripe', 'stripe.com', 'US', 'fintech', 19),
    ('Block', 'squareup.com', 'US', 'fintech', 20),
    ('PayPal', 'paypal.com', 'US', 'fintech', 21),
    ('Shopify', 'shopify.com', 'CA', 'ecommerce', 22),
    ('Spotify', 'spotify.com', 'SE', 'streaming', 23),
    ('Dropbox', 'dropbox.com', 'US', 'software', 24),
    ('Slack', 'slack.com', 'US', 'software', 25),
    ('Zoom', 'zoom.us', 'US', 'software', 26),
    ('Atlassian', 'atlassian.com', 'AU', 'software', 27),
    ('Twilio', 'twilio.com', 'US', 'software', 28),
    ('ServiceNow', 'servicenow.com', 'US', 'software', 29),
    ('Workday', 'workday.com', 'US', 'software', 30),
    ('Snowflake', 'snowflake.com', 'US', 'data', 31),
    ('Databricks', 'databricks.com', 'US', 'data', 32),
    ('Palantir', 'palantir.com', 'US', 'software', 33),
    ('DocuSign', 'docusign.com', 'US', 'software', 34),
    ('Intuit', 'intuit.com', 'US', 'software', 35),
    ('Autodesk', 'autodesk.com', 'US', 'software', 36),
    ('Figma', 'figma.com', 'US', 'design software', 37),
    ('Canva', 'canva.com', 'AU', 'design software', 38),
    ('Notion', 'notion.so', 'US', 'software', 39),
    ('Airtable', 'airtable.com', 'US', 'software', 40),
    ('Asana', 'asana.com', 'US', 'software', 41),
    ('monday.com', 'monday.com', 'IL', 'software', 42),
    ('HubSpot', 'hubspot.com', 'US', 'software', 43),
    ('Pinterest', 'pinterest.com', 'US', 'social media', 44),
    ('Snap', 'snap.com', 'US', 'social media', 45),
    ('LinkedIn', 'linkedin.com', 'US', 'social media', 46),
    ('Reddit', 'reddit.com', 'US', 'social media', 47),
    ('Discord', 'discord.com', 'US', 'social media', 48),
    ('Booking.com', 'booking.com', 'NL', 'travel', 49),
    ('Expedia Group', 'expediagroup.com', 'US', 'travel', 50),
    ('Zillow', 'zillow.com', 'US', 'real estate', 51),
    ('Indeed', 'indeed.com', 'US', 'jobs', 52),
    ('eBay', 'ebay.com', 'US', 'ecommerce', 53),
    ('Etsy', 'etsy.com', 'US', 'ecommerce', 54),
    ('Wayfair', 'wayfair.com', 'US', 'ecommerce', 55),
    ('Walmart', 'walmart.com', 'US', 'retail', 56),
    ('Target', 'target.com', 'US', 'retail', 57),
    ('The Home Depot', 'homedepot.com', 'US', 'retail', 58),
    ('Costco', 'costco.com', 'US', 'retail', 59),
    ('Nike', 'nike.com', 'US', 'apparel', 60),
    ('Starbucks', 'starbucks.com', 'US', 'food and beverage', 61),
    ('McDonald''s', 'mcdonalds.com', 'US', 'food and beverage', 62),
    ('Coca-Cola', 'coca-cola.com', 'US', 'food and beverage', 63),
    ('PepsiCo', 'pepsico.com', 'US', 'food and beverage', 64),
    ('Procter & Gamble', 'pg.com', 'US', 'consumer goods', 65),
    ('Johnson & Johnson', 'jnj.com', 'US', 'healthcare', 66),
    ('Pfizer', 'pfizer.com', 'US', 'pharmaceuticals', 67),
    ('Merck', 'merck.com', 'US', 'pharmaceuticals', 68),
    ('Eli Lilly', 'lilly.com', 'US', 'pharmaceuticals', 69),
    ('AbbVie', 'abbvie.com', 'US', 'pharmaceuticals', 70),
    ('Bristol Myers Squibb', 'bms.com', 'US', 'pharmaceuticals', 71),
    ('Amgen', 'amgen.com', 'US', 'biotech', 72),
    ('UnitedHealth Group', 'uhg.com', 'US', 'healthcare', 73),
    ('CVS Health', 'cvshealth.com', 'US', 'healthcare', 74),
    ('JPMorgan Chase', 'jpmorgan.com', 'US', 'banking', 75),
    ('Bank of America', 'bankofamerica.com', 'US', 'banking', 76),
    ('Wells Fargo', 'wellsfargo.com', 'US', 'banking', 77),
    ('Goldman Sachs', 'goldmansachs.com', 'US', 'banking', 78),
    ('Morgan Stanley', 'morganstanley.com', 'US', 'banking', 79),
    ('Citigroup', 'citigroup.com', 'US', 'banking', 80),
    ('American Express', 'americanexpress.com', 'US', 'financial services', 81),
    ('Visa', 'visa.com', 'US', 'fintech', 82),
    ('Mastercard', 'mastercard.com', 'US', 'fintech', 83),
    ('BlackRock', 'blackrock.com', 'US', 'asset management', 84),
    ('Fidelity Investments', 'fidelity.com', 'US', 'financial services', 85),
    ('Charles Schwab', 'schwab.com', 'US', 'financial services', 86),
    ('The Walt Disney Company', 'disney.com', 'US', 'media', 87),
    ('Warner Bros. Discovery', 'wbd.com', 'US', 'media', 88),
    ('Comcast', 'comcast.com', 'US', 'telecom', 89),
    ('Verizon', 'verizon.com', 'US', 'telecom', 90),
    ('AT&T', 'att.com', 'US', 'telecom', 91),
    ('T-Mobile', 't-mobile.com', 'US', 'telecom', 92),
    ('NBCUniversal', 'nbcuni.com', 'US', 'media', 93),
    ('Paramount', 'paramount.com', 'US', 'media', 94),
    ('Activision Blizzard', 'activisionblizzard.com', 'US', 'gaming', 95),
    ('Electronic Arts', 'ea.com', 'US', 'gaming', 96),
    ('Epic Games', 'epicgames.com', 'US', 'gaming', 97),
    ('Riot Games', 'riotgames.com', 'US', 'gaming', 98),
    ('Roblox', 'roblox.com', 'US', 'gaming', 99),
    ('Unity Technologies', 'unity.com', 'US', 'gaming', 100),
    ('General Motors', 'gm.com', 'US', 'automotive', 101),
    ('Ford Motor Company', 'ford.com', 'US', 'automotive', 102),
    ('Tesla', 'tesla.com', 'US', 'automotive', 103),
    ('Boeing', 'boeing.com', 'US', 'aerospace', 104),
    ('Lockheed Martin', 'lockheedmartin.com', 'US', 'aerospace', 105),
    ('Raytheon Technologies', 'rtx.com', 'US', 'aerospace', 106),
    ('General Electric', 'ge.com', 'US', 'industrial', 107),
    ('Caterpillar', 'caterpillar.com', 'US', 'industrial', 108),
    ('3M', '3m.com', 'US', 'industrial', 109),
    ('Honeywell', 'honeywell.com', 'US', 'industrial', 110),
    ('Dow', 'dow.com', 'US', 'chemicals', 111),
    ('DuPont', 'dupont.com', 'US', 'chemicals', 112),
    ('ExxonMobil', 'exxonmobil.com', 'US', 'energy', 113),
    ('Chevron', 'chevron.com', 'US', 'energy', 114),
    ('UPS', 'ups.com', 'US', 'logistics', 115),
    ('FedEx', 'fedex.com', 'US', 'logistics', 116),
    ('Delta Air Lines', 'delta.com', 'US', 'airlines', 117),
    ('United Airlines', 'united.com', 'US', 'airlines', 118),
    ('American Airlines', 'aa.com', 'US', 'airlines', 119),
    ('Marriott International', 'marriott.com', 'US', 'hospitality', 120),
    ('Hilton', 'hilton.com', 'US', 'hospitality', 121),
    ('Accenture', 'accenture.com', 'IE', 'consulting', 122),
    ('Deloitte', 'deloitte.com', 'GB', 'consulting', 123),
    ('PwC', 'pwc.com', 'GB', 'consulting', 124),
    ('KPMG', 'kpmg.com', 'NL', 'consulting', 125),
    ('Ernst & Young', 'ey.com', 'GB', 'consulting', 126),
    ('McKinsey & Company', 'mckinsey.com', 'US', 'consulting', 127),
    ('Boston Consulting Group', 'bcg.com', 'US', 'consulting', 128),
    ('Bain & Company', 'bain.com', 'US', 'consulting', 129),
    ('Capgemini', 'capgemini.com', 'FR', 'IT services', 130),
    ('Infosys', 'infosys.com', 'IN', 'IT services', 131),
    ('Tata Consultancy Services', 'tcs.com', 'IN', 'IT services', 132),
    ('Wipro', 'wipro.com', 'IN', 'IT services', 133),
    ('HCLTech', 'hcltech.com', 'IN', 'IT services', 134),
    ('Tech Mahindra', 'techmahindra.com', 'IN', 'IT services', 135),
    ('Cognizant', 'cognizant.com', 'US', 'IT services', 136),
    ('DXC Technology', 'dxc.com', 'US', 'IT services', 137),
    ('Kyndryl', 'kyndryl.com', 'US', 'IT services', 138),
    ('NTT Data', 'nttdata.com', 'JP', 'IT services', 139),
    ('Fujitsu', 'fujitsu.com', 'JP', 'IT services', 140),
    ('Hitachi', 'hitachi.com', 'JP', 'industrial', 141),
    ('Sony', 'sony.com', 'JP', 'consumer electronics', 142),
    ('Panasonic', 'panasonic.com', 'JP', 'consumer electronics', 143),
    ('Toshiba', 'toshiba.com', 'JP', 'industrial', 144),
    ('Canon', 'canon.com', 'JP', 'consumer electronics', 145),
    ('Nintendo', 'nintendo.com', 'JP', 'gaming', 146),
    ('Toyota', 'toyota.com', 'JP', 'automotive', 147),
    ('Honda', 'honda.com', 'JP', 'automotive', 148),
    ('Nissan', 'nissan-global.com', 'JP', 'automotive', 149),
    ('Samsung Electronics', 'samsung.com', 'KR', 'consumer electronics', 150),
    ('LG', 'lg.com', 'KR', 'consumer electronics', 151),
    ('Hyundai Motor Group', 'hyundai.com', 'KR', 'automotive', 152),
    ('Alibaba Group', 'alibaba.com', 'CN', 'ecommerce', 153),
    ('Tencent', 'tencent.com', 'CN', 'internet', 154),
    ('ByteDance', 'bytedance.com', 'CN', 'internet', 155),
    ('TikTok', 'tiktok.com', 'US', 'social media', 156),
    ('Baidu', 'baidu.com', 'CN', 'internet', 157),
    ('Xiaomi', 'mi.com', 'CN', 'consumer electronics', 158),
    ('TSMC', 'tsmc.com', 'TW', 'semiconductors', 159),
    ('ASML', 'asml.com', 'NL', 'semiconductors', 160),
    ('SAP', 'sap.com', 'DE', 'software', 161),
    ('Siemens', 'siemens.com', 'DE', 'industrial', 162),
    ('Bosch', 'bosch.com', 'DE', 'industrial', 163),
    ('BMW Group', 'bmwgroup.com', 'DE', 'automotive', 164),
    ('Mercedes-Benz Group', 'mercedes-benz.com', 'DE', 'automotive', 165),
    ('Volkswagen Group', 'volkswagen-group.com', 'DE', 'automotive', 166),
    ('Audi', 'audi.com', 'DE', 'automotive', 167),
    ('Porsche', 'porsche.com', 'DE', 'automotive', 168),
    ('Adidas', 'adidas.com', 'DE', 'apparel', 169),
    ('Puma', 'puma.com', 'DE', 'apparel', 170),
    ('Lufthansa', 'lufthansa.com', 'DE', 'airlines', 171),
    ('Deutsche Telekom', 'telekom.com', 'DE', 'telecom', 172),
    ('Deutsche Bank', 'db.com', 'DE', 'banking', 173),
    ('Allianz', 'allianz.com', 'DE', 'insurance', 174),
    ('BMW Motorrad', 'bmw-motorrad.com', 'DE', 'automotive', 175),
    ('Zalando', 'zalando.com', 'DE', 'ecommerce', 176),
    ('Delivery Hero', 'deliveryhero.com', 'DE', 'food delivery', 177),
    ('N26', 'n26.com', 'DE', 'fintech', 178),
    ('Celonis', 'celonis.com', 'DE', 'software', 179),
    ('Personio', 'personio.com', 'DE', 'software', 180),
    ('Sixt', 'sixt.com', 'DE', 'mobility', 181),
    ('UBS', 'ubs.com', 'CH', 'banking', 182),
    ('Credit Suisse', 'credit-suisse.com', 'CH', 'banking', 183),
    ('Nestlé', 'nestle.com', 'CH', 'food and beverage', 184),
    ('Novartis', 'novartis.com', 'CH', 'pharmaceuticals', 185),
    ('Roche', 'roche.com', 'CH', 'pharmaceuticals', 186),
    ('Zurich Insurance', 'zurich.com', 'CH', 'insurance', 187),
    ('Logitech', 'logitech.com', 'CH', 'consumer electronics', 188),
    ('Lonza', 'lonza.com', 'CH', 'biotech', 189),
    ('ABB', 'abb.com', 'CH', 'industrial', 190),
    ('Rolex', 'rolex.com', 'CH', 'luxury', 191),
    ('Philips', 'philips.com', 'NL', 'health technology', 192),
    ('Heineken', 'heineken.com', 'NL', 'food and beverage', 193),
    ('ING', 'ing.com', 'NL', 'banking', 194),
    ('Adyen', 'adyen.com', 'NL', 'fintech', 195),
    ('KLM', 'klm.com', 'NL', 'airlines', 196),
    ('Ahold Delhaize', 'aholddelhaize.com', 'NL', 'retail', 197),
    ('Shell', 'shell.com', 'GB', 'energy', 198),
    ('BP', 'bp.com', 'GB', 'energy', 199),
    ('Unilever', 'unilever.com', 'GB', 'consumer goods', 200),
    ('HSBC', 'hsbc.com', 'GB', 'banking', 201),
    ('Barclays', 'barclays.com', 'GB', 'banking', 202),
    ('Lloyds Banking Group', 'lloydsbanking.com', 'GB', 'banking', 203),
    ('Standard Chartered', 'sc.com', 'GB', 'banking', 204),
    ('Vodafone', 'vodafone.com', 'GB', 'telecom', 205),
    ('BT Group', 'bt.com', 'GB', 'telecom', 206),
    ('AstraZeneca', 'astrazeneca.com', 'GB', 'pharmaceuticals', 207),
    ('GSK', 'gsk.com', 'GB', 'pharmaceuticals', 208),
    ('Rolls-Royce', 'rolls-royce.com', 'GB', 'aerospace', 209),
    ('BAE Systems', 'baesystems.com', 'GB', 'aerospace', 210),
    ('Burberry', 'burberry.com', 'GB', 'luxury', 211),
    ('Dyson', 'dyson.com', 'GB', 'consumer electronics', 212),
    ('Ocado', 'ocado.com', 'GB', 'ecommerce', 213),
    ('Deliveroo', 'deliveroo.com', 'GB', 'food delivery', 214),
    ('Monzo', 'monzo.com', 'GB', 'fintech', 215),
    ('Revolut', 'revolut.com', 'GB', 'fintech', 216),
    ('Wise', 'wise.com', 'GB', 'fintech', 217),
    ('Checkout.com', 'checkout.com', 'GB', 'fintech', 218),
    ('Farfetch', 'farfetch.com', 'GB', 'ecommerce', 219),
    ('ASOS', 'asos.com', 'GB', 'ecommerce', 220),
    ('BBC', 'bbc.com', 'GB', 'media', 221),
    ('The Guardian', 'theguardian.com', 'GB', 'media', 222),
    ('Financial Times', 'ft.com', 'GB', 'media', 223),
    ('The Economist Group', 'economist.com', 'GB', 'media', 224),
    ('ARM', 'arm.com', 'GB', 'semiconductors', 225),
    ('DeepMind', 'deepmind.com', 'GB', 'AI', 226),
    ('L''Oréal', 'loreal.com', 'FR', 'beauty', 227),
    ('LVMH', 'lvmh.com', 'FR', 'luxury', 228),
    ('Kering', 'kering.com', 'FR', 'luxury', 229),
    ('Chanel', 'chanel.com', 'FR', 'luxury', 230),
    ('Hermès', 'hermes.com', 'FR', 'luxury', 231),
    ('Dior', 'dior.com', 'FR', 'luxury', 232),
    ('Airbus', 'airbus.com', 'FR', 'aerospace', 233),
    ('Air France', 'airfrance.com', 'FR', 'airlines', 234),
    ('Renault Group', 'renaultgroup.com', 'FR', 'automotive', 235),
    ('Stellantis', 'stellantis.com', 'NL', 'automotive', 236),
    ('Sanofi', 'sanofi.com', 'FR', 'pharmaceuticals', 237),
    ('TotalEnergies', 'totalenergies.com', 'FR', 'energy', 238),
    ('BNP Paribas', 'bnpparibas.com', 'FR', 'banking', 239),
    ('Société Générale', 'societegenerale.com', 'FR', 'banking', 240),
    ('AXA', 'axa.com', 'FR', 'insurance', 241),
    ('Michelin', 'michelin.com', 'FR', 'automotive', 242),
    ('Danone', 'danone.com', 'FR', 'food and beverage', 243),
    ('Carrefour', 'carrefour.com', 'FR', 'retail', 244),
    ('Decathlon', 'decathlon.com', 'FR', 'retail', 245),
    ('Dassault Systèmes', '3ds.com', 'FR', 'software', 246),
    ('Ubisoft', 'ubisoft.com', 'FR', 'gaming', 247),
    ('Deezer', 'deezer.com', 'FR', 'streaming', 248),
    ('BlaBlaCar', 'blablacar.com', 'FR', 'mobility', 249),
    ('Doctolib', 'doctolib.com', 'FR', 'healthtech', 250),
    ('Qonto', 'qonto.com', 'FR', 'fintech', 251),
    ('IKEA', 'ikea.com', 'SE', 'retail', 252),
    ('H&M', 'hm.com', 'SE', 'apparel', 253),
    ('Volvo Group', 'volvogroup.com', 'SE', 'automotive', 254),
    ('Ericsson', 'ericsson.com', 'SE', 'telecom', 255),
    ('Electrolux', 'electrolux.com', 'SE', 'consumer goods', 256),
    ('Klarna', 'klarna.com', 'SE', 'fintech', 257),
    ('King', 'king.com', 'SE', 'gaming', 258),
    ('Mojang Studios', 'mojang.com', 'SE', 'gaming', 259),
    ('Maersk', 'maersk.com', 'DK', 'logistics', 260),
    ('Novo Nordisk', 'novonordisk.com', 'DK', 'pharmaceuticals', 261),
    ('Carlsberg', 'carlsberg.com', 'DK', 'food and beverage', 262),
    ('LEGO Group', 'lego.com', 'DK', 'toys', 263),
    ('Pandora', 'pandora.net', 'DK', 'luxury', 264),
    ('Bang & Olufsen', 'bang-olufsen.com', 'DK', 'consumer electronics', 265),
    ('Nokia', 'nokia.com', 'FI', 'telecom', 266),
    ('Supercell', 'supercell.com', 'FI', 'gaming', 267),
    ('Rovio', 'rovio.com', 'FI', 'gaming', 268),
    ('Wolt', 'wolt.com', 'FI', 'food delivery', 269),
    ('Inditex', 'inditex.com', 'ES', 'apparel', 270),
    ('Zara', 'zara.com', 'ES', 'apparel', 271),
    ('Santander', 'santander.com', 'ES', 'banking', 272),
    ('BBVA', 'bbva.com', 'ES', 'banking', 273),
    ('Iberia', 'iberia.com', 'ES', 'airlines', 274),
    ('Telefónica', 'telefonica.com', 'ES', 'telecom', 275),
    ('Repsol', 'repsol.com', 'ES', 'energy', 276),
    ('Glovo', 'glovoapp.com', 'ES', 'food delivery', 277),
    ('Cabify', 'cabify.com', 'ES', 'mobility', 278),
    ('Ferrari', 'ferrari.com', 'IT', 'automotive', 279),
    ('Lamborghini', 'lamborghini.com', 'IT', 'automotive', 280),
    ('Prada', 'prada.com', 'IT', 'luxury', 281),
    ('Gucci', 'gucci.com', 'IT', 'luxury', 282),
    ('Armani', 'armani.com', 'IT', 'luxury', 283),
    ('Barilla', 'barilla.com', 'IT', 'food and beverage', 284),
    ('Ferrero', 'ferrero.com', 'IT', 'food and beverage', 285),
    ('Lavazza', 'lavazza.com', 'IT', 'food and beverage', 286),
    ('Campari Group', 'campari.com', 'IT', 'food and beverage', 287),
    ('Enel', 'enel.com', 'IT', 'energy', 288),
    ('Eni', 'eni.com', 'IT', 'energy', 289),
    ('Leonardo', 'leonardo.com', 'IT', 'aerospace', 290),
    ('Pirelli', 'pirelli.com', 'IT', 'automotive', 291),
    ('Intesa Sanpaolo', 'intesasanpaolo.com', 'IT', 'banking', 292),
    ('UniCredit', 'unicreditgroup.eu', 'IT', 'banking', 293),
    ('Generali', 'generali.com', 'IT', 'insurance', 294),
    ('Benjamin Moore', 'benjaminmoore.com', 'US', 'paint', 295),
    ('Givenchy', 'givenchy.com', 'FR', 'luxury', 296),
    ('Philip Morris International', 'pmi.com', 'US', 'consumer goods', 297),
    ('Nielsen', 'nielsen.com', 'US', 'market research', 298),
    ('Gartner', 'gartner.com', 'US', 'research', 299),
    ('Forrester', 'forrester.com', 'US', 'research', 300),
    ('IDEO', 'ideo.com', 'US', 'design', 301),
    ('frog design', 'frog.co', 'US', 'design', 302),
    ('Pentagram', 'pentagram.com', 'US', 'design', 303),
    ('Landor', 'landor.com', 'US', 'design', 304),
    ('R/GA', 'rga.com', 'US', 'design', 305),
    ('Huge', 'hugeinc.com', 'US', 'design', 306),
    ('Wieden+Kennedy', 'wk.com', 'US', 'advertising', 307),
    ('Ogilvy', 'ogilvy.com', 'US', 'advertising', 308),
    ('Publicis Groupe', 'publicisgroupe.com', 'FR', 'advertising', 309),
    ('WPP', 'wpp.com', 'GB', 'advertising', 310),
    ('Omnicom Group', 'omnicomgroup.com', 'US', 'advertising', 311),
    ('Dentsu', 'dentsu.com', 'JP', 'advertising', 312),
    ('Interpublic Group', 'interpublic.com', 'US', 'advertising', 313),
    ('TBWA', 'tbwa.com', 'US', 'advertising', 314),
    ('BBDO', 'bbdo.com', 'US', 'advertising', 315),
    ('Droga5', 'droga5.com', 'US', 'advertising', 316),
    ('Awwwards', 'awwwards.com', 'US', 'design', 317),
    ('Behance', 'behance.net', 'US', 'design', 318),
    ('Dribbble', 'dribbble.com', 'US', 'design', 319),
    ('Zendesk', 'zendesk.com', 'US', 'software', 320),
    ('Freshworks', 'freshworks.com', 'US', 'software', 321),
    ('Zoho', 'zoho.com', 'IN', 'software', 322),
    ('Postman', 'postman.com', 'US', 'software', 323),
    ('Razorpay', 'razorpay.com', 'IN', 'fintech', 324),
    ('CRED', 'cred.club', 'IN', 'fintech', 325),
    ('PhonePe', 'phonepe.com', 'IN', 'fintech', 326),
    ('Paytm', 'paytm.com', 'IN', 'fintech', 327),
    ('Zerodha', 'zerodha.com', 'IN', 'fintech', 328),
    ('Groww', 'groww.in', 'IN', 'fintech', 329),
    ('Flipkart', 'flipkart.com', 'IN', 'ecommerce', 330),
    ('Myntra', 'myntra.com', 'IN', 'ecommerce', 331),
    ('Meesho', 'meesho.com', 'IN', 'ecommerce', 332),
    ('Nykaa', 'nykaa.com', 'IN', 'ecommerce', 333),
    ('Swiggy', 'swiggy.com', 'IN', 'food delivery', 334),
    ('Zomato', 'zomato.com', 'IN', 'food delivery', 335),
    ('Ola', 'olacabs.com', 'IN', 'mobility', 336),
    ('Urban Company', 'urbancompany.com', 'IN', 'services', 337),
    ('OYO Rooms', 'oyorooms.com', 'IN', 'hospitality', 338),
    ('MakeMyTrip', 'makemytrip.com', 'IN', 'travel', 339),
    ('Dream11', 'dream11.com', 'IN', 'gaming', 340),
    ('Games24x7', 'games24x7.com', 'IN', 'gaming', 341),
    ('MPL', 'mpl.live', 'IN', 'gaming', 342),
    ('ShareChat', 'sharechat.com', 'IN', 'social media', 343),
    ('Dailyhunt', 'dailyhunt.in', 'IN', 'media', 344),
    ('Hotstar', 'hotstar.com', 'IN', 'streaming', 345),
    ('Jio', 'jio.com', 'IN', 'telecom', 346),
    ('Bharti Airtel', 'airtel.in', 'IN', 'telecom', 347),
    ('Vodafone Idea', 'vodafoneidea.com', 'IN', 'telecom', 348),
    ('Reliance Industries', 'ril.com', 'IN', 'conglomerate', 349),
    ('Tata Sons', 'tata.com', 'IN', 'conglomerate', 350),
    ('Tata Motors', 'tatamotors.com', 'IN', 'automotive', 351),
    ('Tata Steel', 'tatasteel.com', 'IN', 'steel', 352),
    ('Titan Company', 'titancompany.in', 'IN', 'luxury', 353),
    ('Mahindra Group', 'mahindra.com', 'IN', 'automotive', 354),
    ('Bajaj Auto', 'bajajauto.com', 'IN', 'automotive', 355),
    ('Hero MotoCorp', 'heromotocorp.com', 'IN', 'automotive', 356),
    ('Maruti Suzuki', 'marutisuzuki.com', 'IN', 'automotive', 357),
    ('Ashok Leyland', 'ashokleyland.com', 'IN', 'automotive', 358),
    ('TVS Motor Company', 'tvsmotor.com', 'IN', 'automotive', 359),
    ('Royal Enfield', 'royalenfield.com', 'IN', 'automotive', 360),
    ('HDFC Bank', 'hdfcbank.com', 'IN', 'banking', 361),
    ('ICICI Bank', 'icicibank.com', 'IN', 'banking', 362),
    ('State Bank of India', 'sbi.co.in', 'IN', 'banking', 363),
    ('Axis Bank', 'axisbank.com', 'IN', 'banking', 364),
    ('Kotak Mahindra Bank', 'kotak.com', 'IN', 'banking', 365),
    ('Yes Bank', 'yesbank.in', 'IN', 'banking', 366),
    ('IDFC First Bank', 'idfcfirstbank.com', 'IN', 'banking', 367),
    ('Bajaj Finserv', 'bajajfinserv.in', 'IN', 'financial services', 368),
    ('HDFC Life', 'hdfclife.com', 'IN', 'insurance', 369),
    ('ICICI Lombard', 'icicilombard.com', 'IN', 'insurance', 370),
    ('LIC', 'licindia.in', 'IN', 'insurance', 371),
    ('Aditya Birla Group', 'adityabirla.com', 'IN', 'conglomerate', 372),
    ('Adani Group', 'adani.com', 'IN', 'conglomerate', 373),
    ('Godrej Group', 'godrej.com', 'IN', 'conglomerate', 374),
    ('ITC Limited', 'itcportal.com', 'IN', 'conglomerate', 375),
    ('Larsen & Toubro', 'larsentoubro.com', 'IN', 'engineering', 376),
    ('Asian Paints', 'asianpaints.com', 'IN', 'paint', 377),
    ('Berger Paints', 'bergerpaints.com', 'IN', 'paint', 378),
    ('Dabur', 'dabur.com', 'IN', 'consumer goods', 379),
    ('Hindustan Unilever', 'hul.co.in', 'IN', 'consumer goods', 380),
    ('Marico', 'marico.com', 'IN', 'consumer goods', 381),
    ('Nestlé India', 'nestle.in', 'IN', 'food and beverage', 382),
    ('Amul', 'amul.com', 'IN', 'food and beverage', 383),
    ('Britannia Industries', 'britannia.co.in', 'IN', 'food and beverage', 384),
    ('ITC Hotels', 'itchotels.com', 'IN', 'hospitality', 385),
    ('Taj Hotels', 'tajhotels.com', 'IN', 'hospitality', 386),
    ('Oberoi Hotels', 'oberoihotels.com', 'IN', 'hospitality', 387),
    ('IndiGo', 'goindigo.in', 'IN', 'airlines', 388),
    ('Air India', 'airindia.com', 'IN', 'airlines', 389),
    ('SpiceJet', 'spicejet.com', 'IN', 'airlines', 390),
    ('Vistara', 'airvistara.com', 'IN', 'airlines', 391),
    ('Infosys BPM', 'infosysbpm.com', 'IN', 'IT services', 392),
    ('Mphasis', 'mphasis.com', 'IN', 'IT services', 393),
    ('Persistent Systems', 'persistent.com', 'IN', 'IT services', 394),
    ('LTIMindtree', 'ltimindtree.com', 'IN', 'IT services', 395),
    ('Zensar Technologies', 'zensar.com', 'IN', 'IT services', 396),
    ('Birlasoft', 'birlasoft.com', 'IN', 'IT services', 397),
    ('Coforge', 'coforge.com', 'IN', 'IT services', 398),
    ('Hexaware', 'hexaware.com', 'IN', 'IT services', 399),
    ('Tata Elxsi', 'tataelxsi.com', 'IN', 'design and technology', 400),
    ('Quest Global', 'quest-global.com', 'IN', 'engineering', 401),
    ('Sasken', 'sasken.com', 'IN', 'engineering', 402),
    ('KPIT', 'kpit.com', 'IN', 'engineering', 403),
    ('Cyient', 'cyient.com', 'IN', 'engineering', 404),
    ('Sonata Software', 'sonata-software.com', 'IN', 'IT services', 405),
    ('Cleartrip', 'cleartrip.com', 'IN', 'travel', 406),
    ('Yatra', 'yatra.com', 'IN', 'travel', 407),
    ('Ixigo', 'ixigo.com', 'IN', 'travel', 408),
    ('PolicyBazaar', 'policybazaar.com', 'IN', 'insurance', 409),
    ('CarDekho', 'cardekho.com', 'IN', 'automotive', 410),
    ('Cars24', 'cars24.com', 'IN', 'automotive', 411),
    ('Unacademy', 'unacademy.com', 'IN', 'edtech', 412),
    ('Byju''s', 'byjus.com', 'IN', 'edtech', 413),
    ('Vedantu', 'vedantu.com', 'IN', 'edtech', 414),
    ('PhysicsWallah', 'pw.live', 'IN', 'edtech', 415),
    ('upGrad', 'upgrad.com', 'IN', 'edtech', 416),
    ('Coursera', 'coursera.org', 'US', 'edtech', 417),
    ('Udemy', 'udemy.com', 'US', 'edtech', 418),
    ('Khan Academy', 'khanacademy.org', 'US', 'edtech', 419),
    ('Duolingo', 'duolingo.com', 'US', 'edtech', 420),
    ('Skillshare', 'skillshare.com', 'US', 'edtech', 421),
    ('Squarespace', 'squarespace.com', 'US', 'software', 422),
    ('Wix', 'wix.com', 'IL', 'software', 423),
    ('Webflow', 'webflow.com', 'US', 'software', 424),
    ('WordPress', 'wordpress.com', 'US', 'software', 425),
    ('Automattic', 'automattic.com', 'US', 'software', 426),
    ('Envato', 'envato.com', 'AU', 'design', 427),
    ('InVision', 'invisionapp.com', 'US', 'design software', 428),
    ('Sketch', 'sketch.com', 'NL', 'design software', 429),
    ('Framer', 'framer.com', 'NL', 'design software', 430),
    ('Miro', 'miro.com', 'NL', 'software', 431),
    ('Loom', 'loom.com', 'US', 'software', 432),
    ('Calendly', 'calendly.com', 'US', 'software', 433),
    ('Grammarly', 'grammarly.com', 'US', 'software', 434),
    ('Typeform', 'typeform.com', 'ES', 'software', 435),
    ('Intercom', 'intercom.com', 'US', 'software', 436),
    ('SurveyMonkey', 'surveymonkey.com', 'US', 'software', 437),
    ('Mural', 'mural.co', 'US', 'software', 438),
    ('Balsamiq', 'balsamiq.com', 'US', 'design software', 439),
    ('Marvel App', 'marvelapp.com', 'GB', 'design software', 440),
    ('Zeplin', 'zeplin.io', 'US', 'design software', 441),
    ('Abstract', 'abstract.com', 'US', 'design software', 442),
    ('LottieFiles', 'lottiefiles.com', 'MY', 'design software', 443),
    ('Maze', 'maze.co', 'NL', 'research software', 444),
    ('UserTesting', 'usertesting.com', 'US', 'research software', 445),
    ('Hotjar', 'hotjar.com', 'MT', 'analytics', 446),
    ('Optimizely', 'optimizely.com', 'US', 'software', 447),
    ('Amplitude', 'amplitude.com', 'US', 'analytics', 448),
    ('Mixpanel', 'mixpanel.com', 'US', 'analytics', 449),
    ('Segment', 'segment.com', 'US', 'analytics', 450),
    ('Braze', 'braze.com', 'US', 'software', 451),
    ('Mailchimp', 'mailchimp.com', 'US', 'software', 452),
    ('Klaviyo', 'klaviyo.com', 'US', 'software', 453),
    ('Datadog', 'datadoghq.com', 'US', 'software', 454),
    ('New Relic', 'newrelic.com', 'US', 'software', 455),
    ('Splunk', 'splunk.com', 'US', 'software', 456),
    ('Elastic', 'elastic.co', 'US', 'software', 457),
    ('MongoDB', 'mongodb.com', 'US', 'software', 458),
    ('Confluent', 'confluent.io', 'US', 'software', 459),
    ('HashiCorp', 'hashicorp.com', 'US', 'software', 460),
    ('Docker', 'docker.com', 'US', 'software', 461),
    ('GitHub', 'github.com', 'US', 'software', 462),
    ('GitLab', 'gitlab.com', 'US', 'software', 463),
    ('JetBrains', 'jetbrains.com', 'CZ', 'software', 464),
    ('Vercel', 'vercel.com', 'US', 'software', 465),
    ('Netlify', 'netlify.com', 'US', 'software', 466),
    ('Cloudflare', 'cloudflare.com', 'US', 'software', 467),
    ('DigitalOcean', 'digitalocean.com', 'US', 'cloud', 468),
    ('HubSpot Inc', 'hubspot.net', 'US', 'software', 469),
    ('OpenAI', 'openai.com', 'US', 'AI', 470),
    ('Anthropic', 'anthropic.com', 'US', 'AI', 471),
    ('Cohere', 'cohere.com', 'CA', 'AI', 472),
    ('Hugging Face', 'huggingface.co', 'US', 'AI', 473),
    ('Mistral AI', 'mistral.ai', 'FR', 'AI', 474),
    ('Scale AI', 'scale.com', 'US', 'AI', 475),
    ('Dataminr', 'dataminr.com', 'US', 'AI', 476),
    ('C3.ai', 'c3.ai', 'US', 'AI', 477),
    ('UiPath', 'uipath.com', 'US', 'automation', 478),
    ('Synthesia', 'synthesia.io', 'GB', 'AI', 479),
    ('Jasper', 'jasper.ai', 'US', 'AI', 480),
    ('Runway', 'runwayml.com', 'US', 'AI', 481),
    ('ElevenLabs', 'elevenlabs.io', 'US', 'AI', 482),
    ('Midjourney', 'midjourney.com', 'US', 'AI', 483),
    ('Stability AI', 'stability.ai', 'GB', 'AI', 484),
    ('Replit', 'replit.com', 'US', 'software', 485),
    ('Stack Overflow', 'stackoverflow.com', 'US', 'software', 486),
    ('Codecademy', 'codecademy.com', 'US', 'edtech', 487),
    ('HackerRank', 'hackerrank.com', 'US', 'software', 488),
    ('LeetCode', 'leetcode.com', 'US', 'software', 489),
    ('Glassdoor', 'glassdoor.com', 'US', 'jobs', 490),
    ('Naukri', 'naukri.com', 'IN', 'jobs', 491),
    ('Foundit', 'foundit.in', 'IN', 'jobs', 492),
    ('Shine', 'shine.com', 'IN', 'jobs', 493),
    ('Times Internet', 'timesinternet.in', 'IN', 'media', 494),
    ('NDTV', 'ndtv.com', 'IN', 'media', 495),
    ('Network18', 'network18online.com', 'IN', 'media', 496),
    ('Zee Entertainment', 'zeel.com', 'IN', 'media', 497),
    ('Sony Pictures Networks India', 'sonypicturesnetworks.com', 'IN', 'media', 498),
    ('PVR INOX', 'pvrcinemas.com', 'IN', 'media', 499),
    ('Balaji Telefilms', 'balajitelefilms.com', 'IN', 'media', 500),
    ('Wipro Consumer Care', 'wiproconsumer.com', 'IN', 'consumer goods', 501),
    ('Godrej Consumer Products', 'godrejcp.com', 'IN', 'consumer goods', 502),
    ('Bombay Dyeing', 'bombaydyeing.com', 'IN', 'textiles', 503),
    ('Raymond', 'raymond.in', 'IN', 'apparel', 504),
    ('FabIndia', 'fabindia.com', 'IN', 'apparel', 505),
    ('Manyavar', 'manyavar.com', 'IN', 'apparel', 506),
    ('Lifestyle', 'lifestylestores.com', 'IN', 'retail', 507),
    ('Shoppers Stop', 'shoppersstop.com', 'IN', 'retail', 508),
    ('Croma', 'croma.com', 'IN', 'retail', 509),
    ('Reliance Digital', 'reliancedigital.in', 'IN', 'retail', 510),
    ('BigBasket', 'bigbasket.com', 'IN', 'ecommerce', 511),
    ('Blinkit', 'blinkit.com', 'IN', 'ecommerce', 512),
    ('Zepto', 'zepto.com', 'IN', 'ecommerce', 513),
    ('Licious', 'licious.in', 'IN', 'ecommerce', 514),
    ('FirstCry', 'firstcry.com', 'IN', 'ecommerce', 515),
    ('Pristyn Care', 'pristyncare.com', 'IN', 'healthtech', 516),
    ('Practo', 'practo.com', 'IN', 'healthtech', 517),
    ('PharmEasy', 'pharmeasy.in', 'IN', 'healthtech', 518),
    ('Apollo Hospitals', 'apollohospitals.com', 'IN', 'healthcare', 519),
    ('Fortis Healthcare', 'fortishealthcare.com', 'IN', 'healthcare', 520),
    ('Max Healthcare', 'maxhealthcare.in', 'IN', 'healthcare', 521),
    ('Narayana Health', 'narayanahealth.org', 'IN', 'healthcare', 522),
    ('Cipla', 'cipla.com', 'IN', 'pharmaceuticals', 523),
    ('Dr. Reddy''s Laboratories', 'drreddys.com', 'IN', 'pharmaceuticals', 524),
    ('Sun Pharmaceutical', 'sunpharma.com', 'IN', 'pharmaceuticals', 525),
    ('Lupin', 'lupin.com', 'IN', 'pharmaceuticals', 526),
    ('Divis Laboratories', 'divislabs.com', 'IN', 'pharmaceuticals', 527),
    ('Biocon', 'biocon.com', 'IN', 'biotech', 528),
    ('Serum Institute of India', 'seruminstitute.com', 'IN', 'biotech', 529),
    ('Godrej Properties', 'godrejproperties.com', 'IN', 'real estate', 530),
    ('DLF', 'dlf.in', 'IN', 'real estate', 531),
    ('Lodha Group', 'lodhagroup.in', 'IN', 'real estate', 532),
    ('Prestige Group', 'prestigeconstructions.com', 'IN', 'real estate', 533),
    ('Ola Electric', 'olaelectric.com', 'IN', 'automotive', 534),
    ('Ather Energy', 'atherenergy.com', 'IN', 'automotive', 535),
    ('BrowserStack', 'browserstack.com', 'IN', 'software', 536),
    ('Chargebee', 'chargebee.com', 'US', 'software', 537),
    ('Vymo', 'vymo.com', 'IN', 'software', 538),
    ('Highradius', 'highradius.com', 'US', 'software', 539),
    ('Darwinbox', 'darwinbox.com', 'IN', 'software', 540),
    ('Yellow.ai', 'yellow.ai', 'IN', 'AI', 541),
    ('Haptik', 'haptik.ai', 'IN', 'AI', 542),
    ('Observe.AI', 'observe.ai', 'IN', 'AI', 543),
    ('Uniphore', 'uniphore.com', 'IN', 'AI', 544),
    ('Cutshort', 'cutshort.io', 'IN', 'jobs', 545),
    ('Instahyre', 'instahyre.com', 'IN', 'jobs', 546),
    ('HackerEarth', 'hackerearth.com', 'IN', 'software', 547),
    ('Hasura', 'hasura.io', 'IN', 'software', 548),
    ('Rippling', 'rippling.com', 'US', 'software', 549),
    ('Gusto', 'gusto.com', 'US', 'software', 550),
    ('Brex', 'brex.com', 'US', 'fintech', 551),
    ('Ramp', 'ramp.com', 'US', 'fintech', 552),
    ('Plaid', 'plaid.com', 'US', 'fintech', 553),
    ('Robinhood', 'robinhood.com', 'US', 'fintech', 554),
    ('Coinbase', 'coinbase.com', 'US', 'fintech', 555),
    ('Chime', 'chime.com', 'US', 'fintech', 556),
    ('Affirm', 'affirm.com', 'US', 'fintech', 557),
    ('Nubank', 'nubank.com.br', 'BR', 'fintech', 558),
    ('Mercado Libre', 'mercadolibre.com', 'AR', 'ecommerce', 559),
    ('Grab', 'grab.com', 'SG', 'mobility', 560),
    ('Gojek', 'gojek.com', 'ID', 'mobility', 561),
    ('Sea Group', 'sea.com', 'SG', 'internet', 562),
    ('Shopee', 'shopee.com', 'SG', 'ecommerce', 563),
    ('Lazada', 'lazada.com', 'SG', 'ecommerce', 564),
    ('Careem', 'careem.com', 'AE', 'mobility', 565),
    ('Talabat', 'talabat.com', 'AE', 'food delivery', 566),
    ('Noon', 'noon.com', 'AE', 'ecommerce', 567),
    ('Emirates', 'emirates.com', 'AE', 'airlines', 568),
    ('Etihad Airways', 'etihad.com', 'AE', 'airlines', 569),
    ('Qatar Airways', 'qatarairways.com', 'QA', 'airlines', 570),
    ('Aramco', 'aramco.com', 'SA', 'energy', 571),
    ('Naspers', 'naspers.com', 'ZA', 'media', 572),
    ('DStv', 'dstv.com', 'ZA', 'media', 573);

  -- One company per name. The slug comes from the database's own
  -- company_slugify(), the same function a member-created company uses, so a
  -- directory row and a proved row can never disagree about what a name's slug
  -- is. created_by stays null: these are directory rows, not a member's company.
  insert into public.companies (
    name, slug, country_code, industry, entity_status,
    source, source_confidence, directory_rank
  )
  select
    seed.name,
    public.company_slugify(seed.name),
    seed.country,
    seed.industry,
    'active',
    'curated-mnc',
    'medium',
    seed.rank
  from _mnc_seed as seed
  on conflict (slug) do nothing;
  get diagnostics v_companies = row_count;

  -- One UNVERIFIED hint per company. `verified = false` and `verified_at =
  -- null` satisfy company_domains_verified_at_check; the partial unique index
  -- on verified domains is untouched, so a domain a member has proved is left
  -- exactly as it is.
  insert into public.company_domains (
    company_id, domain, verified, domain_type, evidence_confidence, source
  )
  select
    company.id,
    lower(btrim(seed.domain)),
    false,
    'primary_website',
    'unknown',
    'curated-mnc'
  from _mnc_seed as seed
  join public.companies as company on company.slug = public.company_slugify(seed.name)
  on conflict (company_id, domain) do nothing;
  get diagnostics v_domains = row_count;

  raise notice 'mnc seed: % companies, % domain hints inserted', v_companies, v_domains;
end
$mnc_seed$;


-- ─── Drop accidental one-character test companies ───────────

-- A one-character company name ("l", "a") is a typo or a test of the picker,
-- never a real employer. Deleting the company cascades its domains,
-- memberships and challenges, and clears any profile that pointed at it — which
-- is precisely "remove it from the work field". Idempotent: nothing matches
-- after the first run.
delete from public.companies
 where slug ~ '^[a-z0-9]$';
