/**
 * Wikipedia photo lookup for master-data rows (cities, sectors, interests,
 * experience levels). Used by the Admin "Fetch images" bulk action.
 *
 * Images come from Wikipedia/Wikimedia Commons — free license and stable
 * CDN URLs. The lookup prefers each page's lead photo at a decent size and
 * falls back to a search hit when no exact page exists.
 */

// Wikimedia's public API asks clients to send a descriptive User-Agent so
// misbehaving bots can be identified. Sequential requests (one per row) are
// well within their rate limits.
const WIKIPEDIA_UA = "FreebuffAdmin/1.0 (admin master-data image sync)";
const WIKIPEDIA_API = "https://en.wikipedia.org/api/rest_v1";
const WIKIPEDIA_ACTION_API = "https://en.wikipedia.org/w/api.php";
const MAX_IMAGE_BYTES = 5 * 1024 * 1024; // match the manual upload limit
const ACCEPTED_IMAGE_TYPES = new Set(["image/jpeg", "image/png", "image/webp"]);

export interface FetchedImage {
  source: string;
  contentType: string;
  bytes: Buffer;
}

interface ThumbPage {
  index?: number;
  title?: string;
  thumbnail?: { source?: string };
  pageprops?: { disambiguation?: string };
}

// Symbol images (flags, coats of arms, seals, logos) are never the photo we
// want. Filenames carry these markers, e.g. "960px-Flag_of_Singapore.svg.png".
const SYMBOL_PATTERNS = [
  /flag[_-]of/i,
  /coat[_-]of[_-]arms/i,
  /locator/i,
  /seal[_-]of/i,
  /logo/i,
  /insignia/i,
];

function isSymbolImage(source: string): boolean {
  const filename = decodeURIComponent(source.split("/").pop() ?? "");
  return SYMBOL_PATTERNS.some((pattern) => pattern.test(filename));
}

/**
 * Resolves a photo for the given query from Wikipedia:
 *  1. The REST summary resolves the canonical page title (handles redirects)
 *     and gives a fallback lead-image thumbnail.
 *  2. The action API asks for a larger (~640px) canonical thumbnail of the
 *     page — reliably generated by Wikimedia, unlike hand-rewritten widths.
 *  3. If the page has no usable photo (no lead image, or the lead image is a
 *     symbol like a flag — e.g. "Austin" resolves to a disambiguation page),
 *     search Wikipedia and pick the top non-disambiguation result with a
 *     photo (e.g. "Austin, Texas").
 * Returns null when no usable image can be found.
 */
export async function findWikipediaImage(query: string): Promise<FetchedImage | null> {
  const summary = await fetchWithRetry(
    `${WIKIPEDIA_API}/page/summary/${encodeURIComponent(query)}`,
    { headers: { "User-Agent": WIKIPEDIA_UA, Accept: "application/json" } }
  );
  const summaryData = summary
    ? ((await summary.json().catch(() => null)) as { title?: string; thumbnail?: { source?: string } } | null)
    : null;
  const title = summaryData?.title ?? query;
  const fallbackSource = summaryData?.thumbnail?.source;

  const candidates: string[] = [];
  const largeSource = await queryPageThumbnail(title);
  if (largeSource && !isSymbolImage(largeSource)) candidates.push(largeSource);
  if (fallbackSource && !isSymbolImage(fallbackSource)) candidates.push(fallbackSource);

  if (candidates.length === 0) {
    // No exact page with a usable photo — search, trying a couple of query
    // variants (e.g. "Senior Designers" → "Senior Designer") to catch rows
    // whose Wikipedia article uses the singular form.
    for (const variant of searchQueryVariants(query)) {
      const searchSource = await searchThumbnail(variant);
      if (searchSource) {
        candidates.push(searchSource);
        break;
      }
    }
  }

  for (const candidate of candidates) {
    const image = await downloadImage(candidate);
    if (image) return image;
  }
  return null;
}

/** Requests the page's lead thumbnail at ~640px via the action API. */
async function queryPageThumbnail(title: string): Promise<string | null> {
  const params = new URLSearchParams({
    action: "query",
    titles: title,
    prop: "pageimages",
    piprop: "thumbnail",
    pithumbsize: "640",
    format: "json",
  });
  const res = await fetchWithRetry(`${WIKIPEDIA_ACTION_API}?${params}`, {
    headers: { "User-Agent": WIKIPEDIA_UA },
  });
  if (!res) return null;
  const data = (await res.json().catch(() => null)) as { query?: { pages?: Record<string, ThumbPage> } } | null;
  const page = Object.values(data?.query?.pages ?? {})[0];
  return page?.thumbnail?.source ?? null;
}

/**
 * Fallback for pages without a usable lead photo (disambiguation entries,
 * symbols, or no page at all): search for the query and return the first
 * non-disambiguation hit with a real photo.
 */
async function searchThumbnail(query: string): Promise<string | null> {
  const params = new URLSearchParams({
    action: "query",
    generator: "search",
    gsrsearch: query,
    gsrlimit: "5",
    prop: "pageimages|pageprops",
    piprop: "thumbnail",
    pithumbsize: "640",
    format: "json",
  });
  const res = await fetchWithRetry(`${WIKIPEDIA_ACTION_API}?${params}`, {
    headers: { "User-Agent": WIKIPEDIA_UA },
  });
  if (!res) return null;
  const data = (await res.json().catch(() => null)) as { query?: { pages?: Record<string, ThumbPage> } } | null;
  const pages = Object.values(data?.query?.pages ?? {})
    .sort((a, b) => (a.index ?? 0) - (b.index ?? 0));
  const hit = pages.find(
    (page) => page.thumbnail?.source && !page.pageprops?.disambiguation && !isSymbolImage(page.thumbnail.source)
  );
  return hit?.thumbnail?.source ?? null;
}

/** Query variants to try when the exact name has no Wikipedia page with a photo. */
function searchQueryVariants(query: string): string[] {
  const variants = [query];
  const trimmed = query.trim();
  if (trimmed.length > 2 && trimmed.endsWith("s") && !trimmed.endsWith("ss")) {
    variants.push(trimmed.slice(0, -1));
  }
  return variants;
}

/** Fetches with a short retry/backoff so Wikimedia rate limits (429) don't fail a row. */
async function fetchWithRetry(
  url: string,
  init: RequestInit,
  attempts = 3
): Promise<Response | null> {
  for (let attempt = 1; attempt <= attempts; attempt++) {
    try {
      const res = await fetch(url, init);
      if (res.status === 429 || res.status >= 500) {
        await new Promise((resolve) => setTimeout(resolve, 500 * attempt));
        continue;
      }
      return res;
    } catch {
      if (attempt === attempts) return null;
      await new Promise((resolve) => setTimeout(resolve, 500 * attempt));
    }
  }
  return null;
}

async function downloadImage(source: string): Promise<FetchedImage | null> {
  const res = await fetchWithRetry(source, { headers: { "User-Agent": WIKIPEDIA_UA } });
  if (!res) return null;
  const contentType = (res.headers.get("content-type") ?? "").split(";")[0].trim();
  if (!ACCEPTED_IMAGE_TYPES.has(contentType)) return null;
  const bytes = Buffer.from(await res.arrayBuffer());
  if (bytes.length === 0 || bytes.length > MAX_IMAGE_BYTES) return null;
  return { source, contentType, bytes };
}